### ISSUE TITLE
Update for Bundesliga

### ISSUE THREAD

**Issue by T3rm1** [fpoppinga/kicktipp-bot#3]
Could you update it for the current Bundesliga season? It only fills out the first page.

**Comment by fpoppinga** [comment]
Hi @T3rm1, 

thanks for creating this issue! 

Sadly implementing multi-page fill-out, because the bot relies exclusively on the btwin quota displayed per Spieltag. As far as I can see from the kicktipp page, they only show the quota for the current Spieltag. 

Of course it would be possible to create a smarter prediciton engine (cf. https://github.com/fpoppinga/kicktipp-bot/blob/master/src/predictor/predictor.ts#L46), which uses other data, but I definitely don't have enough time to do this right now. Maybe for the world cup 2020 ;-).

Best
Finn

**Comment by leber33** [comment]
I'm working on a better prediction engine using https://www.predictz.com/predictions/germany/bundesliga/ 

I keep you posted
